/*
   driverfox.h

NE PAS MODIFIER sauf utilisateur averti

*/
#ifndef __DRIVERFOX_H
#define __DRIVERFOX_H


typedef struct {
	unsigned kernelID;
	int request;
	int export;
	int change;
	int dir;
	int value;
}
T_GPIO;

#define NOINIT 0
#define INIT 1
#define DIRIN 0
#define DIROUT 1

static T_GPIO gpioa[8] = {
	{ FOXG20_KID_PA0, NOINIT, NOINIT, NOINIT, NOINIT} ,
	{ FOXG20_KID_PA1, NOINIT, NOINIT, NOINIT, NOINIT} ,
	{ FOXG20_KID_PA2, NOINIT, NOINIT, NOINIT, NOINIT} ,
	{ FOXG20_KID_PA3, NOINIT, NOINIT, NOINIT, NOINIT} ,
	{ FOXG20_KID_PA4, NOINIT, NOINIT, NOINIT, NOINIT} ,
	{ FOXG20_KID_PA5, NOINIT, NOINIT, NOINIT, NOINIT} ,
	{ FOXG20_KID_PA6, NOINIT, NOINIT, NOINIT, NOINIT} ,
	{ FOXG20_KID_PA7, NOINIT, NOINIT, NOINIT, NOINIT} ,
};

static T_GPIO gpiob[8] = {
	{ FOXG20_KID_PB0, NOINIT, NOINIT, NOINIT, NOINIT} ,
	{ FOXG20_KID_PB1, NOINIT, NOINIT, NOINIT, NOINIT} ,
	{ FOXG20_KID_PB2, NOINIT, NOINIT, NOINIT, NOINIT} ,
	{ FOXG20_KID_PB3, NOINIT, NOINIT, NOINIT, NOINIT} ,
	{ FOXG20_KID_PB4, NOINIT, NOINIT, NOINIT, NOINIT} ,
	{ FOXG20_KID_PB5, NOINIT, NOINIT, NOINIT, NOINIT} ,
	{ FOXG20_KID_PB6, NOINIT, NOINIT, NOINIT, NOINIT} ,
	{ FOXG20_KID_PB7, NOINIT, NOINIT, NOINIT, NOINIT} ,
};

  
#endif  
